// This is a list of error codes that are returned by MongoDB.
// Use this list to check for specific errors.

const MONGOC_ERROR_COLLECTION_DOES_NOT_EXIST = 26;
const MONGOC_ERROR_WRITE_CONCERN_ERROR = 64;
const MONGOC_ERROR_DUPLICATE_KEY = 11000;
const MONGOC_ERROR_MAX_TIME_MS_EXPIRED = 50;
const MONGOC_ERROR_PROTOCOL_ERROR = 17;
const MONGOC_ERROR_SERVER_SELECTION_FAILURE = 15;
const MONGOC_ERROR_QUERY_COMMAND_NOT_FOUND = 59;
